root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o tmp/main ./cmd/server"
  bin = "tmp/main"
  include_ext = ["go", "html"]
  exclude_dir = ["tmp", "vendor", "testdata"]
  stop_on_error = true

[log]
  time = true
