server:
  port: 8080

rate_limit:
  enabled: true
  rps: 5
  burst: 10

redis:
  enabled: true
  addr: ""
  password: ""
  db: 0

log:
  level: info
  format: json
  output: stdout
s3:
  enabled: false
  addr: "ap-southeast-2"
postgres:
  enabled: false
  addr: "localhost:5432"
  user: postgres
  password: postgres
  db: app
