server:
  port: 8080

rate_limit:
  enabled: true
  rps: 5
  burst: 10

redis:
  enabled: true
  addr: ""
  password: ""
  db: 0

maze_service:
  url: "http://localhost:3000"


log:
  level: info
  format: json
  output: stdout

cors:
  allowed_origins:
    - "http://localhost:5173"
    - "https://high-contention-resource-allocation.vercel.app"
    - "https://www.eddiekhean.site"
    - "https://eddiekhean.site"
    - "https://www.eddiekhean.site/"
