server:
  port: 8080

rate_limit:
  enabled: true
  rps: 5
  burst: 10

redis:
  enabled: true
  addr: ""
  password: ""
  db: 0

maze_service:
  url: "http://localhost:8000"


log:
  level: info
  format: json
  output: stdout
