server:
  port: 8080

rate_limit:
  enabled: true
  rps: 5
  burst: 10

redis:
  enabled: true
  addr: ""
  password: ""
  db: 0

log:
  level: info
  format: json
  output: stdout
s3:
  enabled: true
  addr: "ap-southeast-2"
  access_key: ""
  secret_key: ""
  bucket: ""

postgres:
  enabled: true
  addr: "localhost:5432"
  user: postgres
  password: postgres
  db: app
image:
  match_threshold: 5
  prefix_range: 1
