server:
  port: 8080

rate_limit:
  enabled: true
  rps: 5
  burst: 10

redis:
  enabled: true
  addr: ""
  password: ""
  db: 0

log:
  level: debug
  format: json
  output: stdout
auth:
  signing_method: "RS256"
  access_expiration_seconds: 3600
  refresh_expiration_seconds: 604800
  private_key_path: "certs/id_rsa"
  public_key_path: "certs/id_rsa.pub"
s3:
  enabled: true
  addr: "ap-southeast-2"
  access_key: ""
  secret_key: ""
  bucket: ""

postgres:
  enabled: true
  addr: "localhost:5432"
  user: postgres
  password: postgres
  db: app
image:
  match_threshold: 5
  prefix_range: 1
cors:
  allowed_origins:
    - "http://localhost:5173"
    - "http://localhost:5174"
    - "https://high-contention-resource-allocation.vercel.app"
    - "https://www.eddiekhean.site"
    - "https://eddiekhean.site"
